#!/usr/bin/env bash
# install haproxy in a new server
sudo apt -y update
sudo apt install -y haproxy

OUT=/etc/haproxy/haproxy.cfg
  
cat <<EOF >>$OUT
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 217124-web-01 100.26.178.148:80 check
   server 217124-web-02 3.90.82.249:80 check
EOF
echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
