#!/usr/bin/env bash
# Configuration of an Nginx Server to listen on port 80.
# Remove the default configuration for Nginx file
rm /etc/nginx/sites-enabled/default
# configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx
service nginx restart
