#!/usr/bin/env bash
# Creates a symbolic link (-s option) between the Nginx configuration file
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
